### ISSUE TITLE
Cant pick a file after clicking, "Recover Project"

### ISSUE THREAD

**Issue by Maxs6391** [bruvzg/gdsdecomp#105]
### System information

Linux Mint 21 Cinnamon

### Issue description

When I try to go and pick a file for recovery, it opens up the "pick a file" box but its completely black and after a couple seconds it will close it self 
![image](https://user-images.githubusercontent.com/68064198/206868082-b78a84de-54d4-4339-a901-a41d4958a9ce.png)

### Steps to reproduce

1/ Open GRDE up 
2/ Click on RE Project and choose "Recover project..."
3/ Wait a sec and program will close it self

### Recovery log

N/A

**Comment by nikitalita** [comment]
this may be a GUI/Display issue; can you post what GPU and graphics card you are using?

**Comment by nikitalita** [comment]
Also, do you have files on your system that are in another script, like Chinese, Thai, etc.? This may be related to a [fontconfig issue on Godot master that I just fixed](https://github.com/godotengine/godot/pull/69785). I have resynced with master on this PR; after this finishes building, can you try the "standalone" artifact from this run and see if that fixes it? https://github.com/bruvzg/gdsdecomp/actions/runs/3666183733

**Comment by Maxs6391** [comment]
> this may be a GUI/Display issue; can you post what GPU and graphics card you are using?
Its Intel Corporation Core Processor Integrated Graphics Controller 



> Also, do you have files on your system that are in another script, like Chinese, Thai, etc.? This may be related to a [fontconfig issue on Godot master that I just fixed](https://github.com/godotengine/godot/pull/69785). I have resynced with master on this PR; after this finishes building, can you try the "standalone" artifact from this run and see if that fixes it? https://github.com/bruvzg/gdsdecomp/actions/runs/3666183733
Soo I have tried doing both the things you asked, and its still the same result as before

**Comment by nikitalita** [comment]
I need the GPU and drivers you're using in order to debug this further.

**Comment by Maxs6391** [comment]
![image](https://user-images.githubusercontent.com/68064198/206892221-50281004-e66c-42ca-824d-0ef34c602e93.png)
Will this do ? sorry, I miss read your comment last time

**Comment by nikitalita** [comment]
That's fine; Yeah, you're running an old Intel HD Graphics GPU, this probably doesn't have proper support for Vulkan; though, the errors I've encountered with that previously just failed to start entirely. 
Does the Godot 4.x (not 3.x) editor run correctly? Download it here: https://downloads.tuxfamily.org/godotengine/4.0/beta7/
In either case, you can attempt the workarounds I have listed here: https://github.com/bruvzg/gdsdecomp/issues/102
Failing that, just run it in CLI mode.

**Comment by Maxs6391** [comment]
So I have tried to run Godot 4.x, It just outright doesn't open like you have tried. I just went to using the CLI mode because I have tried updating my drivers before but to no avail. Thank you a lot for your help!
