### ISSUE TITLE
Scene exported scripted SubResources do not follow correct order, causing property loss

### ISSUE THREAD

**Issue by HappyDOGE** [bruvzg/gdsdecomp#213]
### System information

Windows 11

### Issue description

When exporting scenes, the SubResources in that scene are exported without postprocessing required by Godot (at least 4.1.1) to load scripted SubResources - the `script` property must be specified first, or else the load will silently fail. The exporter specifies the `script` property last.
This causes an issue with array elements being silently reset to default/null values (#158).
Manually moving the `script` property to the top of all SubResources works and the scene is populated in the editor as expected.

### Steps to reproduce

Tested on Buckshot Roulette v2.0.0-STEAM

### Recovery log

[gdre_export.log](https://github.com/user-attachments/files/17611799/gdre_export.log)

**Comment by nikitalita** [comment]
I just fixed an issue with typed arrays/dicts in this PR; could you give this a shot and see if that fixes it? https://github.com/bruvzg/gdsdecomp/actions/runs/11653896008

If that doesn't work, could you point me to an example of a resource that is affected by this?

**Comment by HappyDOGE** [comment]
Hi, unfortunately that doesn't fix it, as the `script` SubResource property (highlighted in red):
![image](https://github.com/user-attachments/assets/868f520b-6c5e-4cfd-bfb3-a9431a597837)
is still set last. When it's set the script's export vars are loaded into the parser to load the properties for the SubResource, so if it's set last the properties loaded before it are simply skipped.
Putting the `script` property first makes them load and show in the editor properly.

**Comment by nikitalita** [comment]
I tested this myself and I've verified that resources with script properties now have theirs at the top, please give this artifact a try:
https://github.com/nikitalita/gdsdecomp/actions/runs/11678325911

**Comment by HappyDOGE** [comment]
It seems to be exported and loaded correctly now, thank you!
